// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rEfCz2iwr7rKqS5mwAwHSJ
// Component: uvbpI5kp2cZB5y
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: q0ZcqhicNTByrb/component
import ProductCard from "../../ProductCard"; // plasmic-import: XnnzAWz-1wmuax/component
import Ratings from "../../Ratings"; // plasmic-import: LN1oqcvcc_f0mJ/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: fZj-J9nF5TsCnZ/component
import BlogPost from "../../BlogPost"; // plasmic-import: 8glfZ7xZvSyklt/component
import Footer from "../../Footer"; // plasmic-import: LxqqBSLRZqOTHn/component
import { useScreenVariants as useScreenVariantseBz5EHfWhcIiS } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: eBz5eHfWHCIiS/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_dirt.module.css"; // plasmic-import: rEfCz2iwr7rKqS5mwAwHSJ/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: uvbpI5kp2cZB5y/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: SdHLg82cM54O1P/icon
import galinaNMiziNqvJx5MUnsplashjpgV70GzeErt6S0Yu from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: V70GzeErt6s0Yu/picture
import igorSonFvPxCqgtwcUnsplashjpgN5SKfMjAGrb6MG from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: n5sKfMjAGrb6mG/picture
import scottWebbORwRlTgBrPoUnsplashjpgYXbPZp3Of2SeDb from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: yXbPZp3of2SEDb/picture
import freddieMarriageUcfKyTanLuUnsplashjpgRgtEv7KMoLbIf from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: rgtEV7kMOLbIf-/picture
import f2MhOuu7AKu8Qiwc from "./images/f2.jpg"; // plasmic-import: MHOuu7aKU8qiwc/picture
import f39ESkX5MnA4OmJ from "./images/f3.jpg"; // plasmic-import: 9E-skX5mnA4OmJ/picture
import f4HvF0BwctgBsZff from "./images/f4.jpg"; // plasmic-import: HvF0bwctgBsZff/picture
import b1QWpAql63Mx1UAq from "./images/b1.jpg"; // plasmic-import: qWPAql63MX1UAq/picture
import b2BlWnekameYlx19 from "./images/b2.jpg"; // plasmic-import: blWnekameYLX19/picture
import b33Zj4DO5GeyBvDf from "./images/b3.jpg"; // plasmic-import: 3ZJ4dO5GeyBvDf/picture
import adidasEv7J7DqGrGjCXb from "./images/adidas.png"; // plasmic-import: ev7j7dqGRGjCXb/picture
import hmJrkDtbtLWaOn83 from "./images/hm.png"; // plasmic-import: JRKDtbtLWaOn83/picture
import kappaWTg02Mowuh2B9T from "./images/kappa.png"; // plasmic-import: wTG02mowuh2b9t/picture
import lacosteKaj68TYyQaajMw from "./images/lacoste.png"; // plasmic-import: kaj68TYyQaajMw/picture
import levisRvI7PgNQj5Wtp from "./images/levis.png"; // plasmic-import: rvI7pgN-qj5Wtp/picture
import plant6JpgB3Gq3ZAekJbuLc from "./images/plant6Jpg.png"; // plasmic-import: B3GQ3ZAekJbuLC/picture
import plant1JpgRAdDYz8MyDkS from "./images/plant1Jpg.png"; // plasmic-import: RAd-dYZ8_myDkS/picture
import plant7JpgWjdzKzGHwgArMj from "./images/plant7Jpg.png"; // plasmic-import: wjdzKzGHwgArMj/picture
import plant5Jpg87CkkxJq8TwWy from "./images/plant5Jpg.png"; // plasmic-import: 87CkkxJq8_twWy/picture
import plant41JpgJ0Bpw3RnQhK52G from "./images/plant41Jpg.png"; // plasmic-import: j0Bpw3RnQhK52G/picture
import plant31JpgCwRmsW4GcUuPh from "./images/plant31Jpg.png"; // plasmic-import: cw_RmsW4GCUuPH/picture
import plant9WebpUsoMy0ATmIqUzr from "./images/plant9Webp.webp"; // plasmic-import: UsoMY0aTMIqUzr/picture
import plant2Webp4KIh9NfpprJseA from "./images/plant2Webp.webp"; // plasmic-import: 4kIh9nfpprJseA/picture
import nanTalkwebpOgTgXqSkF0Fc8R from "./images/nanTalkwebp.webp"; // plasmic-import: OgTgXqSkF0fc8R/picture
import teamwebpGOvwC2TNreKQk7 from "./images/teamwebp.webp"; // plasmic-import: GOvwC2tNreKQk7/picture

export const PlasmicAboutUs__VariantProps = new Array();

export const PlasmicAboutUs__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicAboutUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantseBz5EHfWhcIiS()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox___84Zuq)}>
              {(
                hasVariant(globalVariants, "screen", "mobile") ? true : true
              ) ? (
                <Header2
                  className={classNames("__wab_instance", sty.header2__ydSe)}
                />
              ) : null}
              <div className={classNames(projectcss.all, sty.freeBox__yRlqs)}>
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"foreground2"}
                  data-plasmic-override={overrides.foreground2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.foreground2)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qe0H)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"We are Planty"}
                    </h1>
                    {true ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___0Bc2Q
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vo4VC
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobile")
                            ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                            : "Well, not really. We’re Snipcart —a bunch of geeks from Québec City. Planty is a theme we built for Stackbit , a killer JAMstack site-builder. To enable e-commerce on Planty, you’ll need to sign up for Snipcart. Testing is forever free, no credit card required."}
                        </div>
                      </div>
                    ) : null}
                  </p.Stack>
                </p.Stack>
              </div>
            </div>
          ) : null}
          {true ? (
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___26BxB)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wNuOw)}>
                  {true ? (
                    <Header2
                      className={classNames(
                        "__wab_instance",
                        sty.header2__eL2M
                      )}
                    />
                  ) : null}
                </div>
              </p.Stack>
              {true ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox___4GtSd)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__e0Rrd
                    )}
                  >
                    {"Top Collections"}
                  </h2>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___2UNo5)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__pTTgm)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__gjdI
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__tb0Lw)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: galinaNMiziNqvJx5MUnsplashjpgV70GzeErt6S0Yu,
                            fullWidth: 1920,
                            fullHeight: 1278,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$65.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__i55WP
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__v9JlE)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__n2ZuD
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___3Sh6)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: igorSonFvPxCqgtwcUnsplashjpgN5SKfMjAGrb6MG,
                            fullWidth: 640,
                            fullHeight: 481,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$80.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__kLpXi
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__hEas2)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__zqxsf
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__sdOIc)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: scottWebbORwRlTgBrPoUnsplashjpgYXbPZp3Of2SeDb,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$40.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__sXwU
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__eAqRf)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__kuJgo
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__daWgB)}
                          displayHeight={"100%"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: freddieMarriageUcfKyTanLuUnsplashjpgRgtEv7KMoLbIf,
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      onSale={true}
                      price={"$100.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__q4Lye
                          )}
                          numReviews={"(45 Review)"}
                        />
                      }
                      title={"Product"}
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <FeatureItem
                  data-plasmic-name={"featureItem"}
                  data-plasmic-override={overrides.featureItem}
                  className={classNames("__wab_instance", sty.featureItem)}
                />
              ) : null}
              {true ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox___1BaVa)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tbAgD
                    )}
                  >
                    {"Featured Products"}
                  </div>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__tv8YD)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__juCsK)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__ks2Rv
                      )}
                      price={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vLgP4
                          )}
                        >
                          {"$160.00"}
                        </div>
                      }
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__y4Xxo
                          )}
                          numReviews={"(12 Review)"}
                          stars={"two"}
                        />
                      }
                      title={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hVN
                          )}
                        >
                          {"Designed Sofa"}
                        </div>
                      }
                      withReviews={true}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__o4QVt)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__i450M
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yzi17)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f2MhOuu7AKu8Qiwc,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$200.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__dxXcR
                          )}
                          stars={"four"}
                        />
                      }
                      title={"Dining Table"}
                      withReviews={true}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__vqFDg)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__lhjWs
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__s39M)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f39ESkX5MnA4OmJ,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$100.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__wrQc
                          )}
                          numReviews={"(23 Review)"}
                          stars={"five"}
                        />
                      }
                      title={"Chair and Table"}
                      withReviews={true}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__szaaQ)}
                  >
                    <ProductCard
                      className={classNames(
                        "__wab_instance",
                        sty.productCard__d0AQb
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___7IAXw)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: f4HvF0BwctgBsZff,
                            fullWidth: 270,
                            fullHeight: 310,
                            aspectRatio: undefined
                          }}
                        />
                      }
                      price={"$299.00"}
                      ratings={
                        <Ratings
                          className={classNames(
                            "__wab_instance",
                            sty.ratings__s8OCj
                          )}
                          numReviews={"(35 Review)"}
                        />
                      }
                      title={"Modern Arm Chair"}
                      withReviews={true}
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__jjDnv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fu71J
                    )}
                  >
                    {"Latest Blog"}
                  </div>
                </div>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__zKjtZ)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__rfNev)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost___3VGt7
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__aitAt)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b1QWpAql63Mx1UAq,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__yC6Am)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost__wWm5U
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__pOji)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b2BlWnekameYlx19,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__xeJj2)}
                  >
                    <BlogPost
                      className={classNames(
                        "__wab_instance",
                        sty.blogPost__g7Y1U
                      )}
                      image={
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__pnmt)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"none"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          src={{
                            src: b33Zj4DO5GeyBvDf,
                            fullWidth: 370,
                            fullHeight: 250,
                            aspectRatio: undefined
                          }}
                        />
                      }
                    />
                  </div>
                </p.Stack>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gr1Sp)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wz6Ng)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"90px"}
                    src={{
                      src: adidasEv7J7DqGrGjCXb,
                      fullWidth: 90,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yPHh2)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"91px"}
                    src={{
                      src: hmJrkDtbtLWaOn83,
                      fullWidth: 91,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___1Pgmu)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"98px"}
                    src={{
                      src: kappaWTg02Mowuh2B9T,
                      fullWidth: 98,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vnV)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"124px"}
                    src={{
                      src: lacosteKaj68TYyQaajMw,
                      fullWidth: 124,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__c1Dw6)}
                    displayHeight={"60px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"125px"}
                    src={{
                      src: levisRvI7PgNQj5Wtp,
                      fullWidth: 125,
                      fullHeight: 60,
                      aspectRatio: undefined
                    }}
                  />
                </p.Stack>
              ) : null}
              {true ? (
                <Footer
                  className={classNames("__wab_instance", sty.footer___4SLwc)}
                />
              ) : null}
            </div>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"bigPlants"}
              data-plasmic-override={overrides.bigPlants}
              hasGap={true}
              className={classNames(projectcss.all, sty.bigPlants)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cidAh)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__qSzG1
                    )}
                  >
                    {"Big plants"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___89Qe3)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__eFzmT)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__pwhS)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant6JpgB3Gq3ZAekJbuLc,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__t4ZBn)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___8KHck)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ouAeZ)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__gBAnD
                      )}
                    >
                      {"Donec finibus"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hlQvj
                      )}
                    >
                      {"bigplants"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__ncIub
                      )}
                    >
                      {"$100.00"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__cxGjX)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__swM5)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant1JpgRAdDYz8MyDkS,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mwFiC)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__rWKbY)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__j4Wf)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__e7TpY
                      )}
                    >
                      {"Nulla suscipit"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bQaFo
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__kcYrZ
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__hl7He)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ccj8B)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant7JpgWjdzKzGHwgArMj,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__huN9E)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__pZ0Uc)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bkNva)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___83Vpe
                      )}
                    >
                      {"Sed consectetur"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uy5Ed
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__s3RO
                      )}
                    >
                      {"$18.40 "}
                    </h5>
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zLvW)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant5Jpg87CkkxJq8TwWy,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1GXyd
                      )}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___2E7Rd)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zNyFz)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__yRu
                      )}
                    >
                      {"Vestibulum eget"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dsB8
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__sA55B
                      )}
                    >
                      {"$220.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"cactuses"}
              data-plasmic-override={overrides.cactuses}
              hasGap={true}
              className={classNames(projectcss.all, sty.cactuses)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__aLoir)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__sy6Oz
                    )}
                  >
                    {"Cactuses"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__pLnHf)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__gEm8W)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__wxnoq)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant41JpgJ0Bpw3RnQhK52G,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h0Z4X)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__h2X8)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dKzKn)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___3BBn8
                      )}
                    >
                      {"Cras molestie"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6JjeB
                      )}
                    >
                      {"cactuses "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___0Exob
                      )}
                    >
                      {"$24.99"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__pNoSq)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___2H7G)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant31JpgCwRmsW4GcUuPh,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__l9ZqJ)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__zZmIy)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox___3K8PK)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__pCt4P
                      )}
                    >
                      {"Curabitur eu tempor"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__p3Ry
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__zmeOr
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__wdf6)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rcXex)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant9WebpUsoMy0ATmIqUzr,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___7LW9Y
                      )}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__cYqkh)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dcX0X)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__jy0Dn
                      )}
                    >
                      {"Fusce sagittis"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xZrZk
                      )}
                    >
                      {"Fusce sagittis"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__yK14X
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__its4U)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__z45L2)}
                    displayHeight={"270px /* plasmic-token: eSOsPoHMXcjvTf */"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: plant2Webp4KIh9NfpprJseA,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rAcsS)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___8Yytr)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dwYmp)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mA627
                      )}
                    >
                      {"Integer porta"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lLkfZ
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__pMhjd
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <div
              data-plasmic-name={"weLove"}
              data-plasmic-override={overrides.weLove}
              className={classNames(projectcss.all, sty.weLove)}
            >
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__bnuc7)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__njWuo)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__maQep)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___8K43)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "400px"
                            : "500px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"500px"}
                        loading={"lazy"}
                        src={{
                          src: nanTalkwebpOgTgXqSkF0Fc8R,
                          fullWidth: 1000,
                          fullHeight: 1498,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column___0Do8J)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2___4XuDc
                        )}
                      >
                        {"Testimonials"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__n86EN
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                          : "Now THAT is true, but we love web development even more. We talk about it on our blog, like, a lot.  We often craft live demos and open source these bad boys on GitHub. Matter of fact, this Planty theme is open source too! If you spot any bugs, open an issue, and we’ll fire our junior dev. Just kidding Michael, you’re good."}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              ) : null}
            </div>
          ) : null}
          {true ? (
            <div
              data-plasmic-name={"weThink"}
              data-plasmic-override={overrides.weThink}
              className={classNames(projectcss.all, sty.weThink)}
            >
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__dk0IO)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__g668Y)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__zInZ)}
                    >
                      <h2
                        className={classNames(
                          projectcss.all,
                          projectcss.h2,
                          projectcss.__wab_text,
                          sty.h2__ry4Vw
                        )}
                      >
                        {"We think plants are the future"}
                      </h2>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__kmDw6
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobile")
                          ? "I didn't know the Snipcart guys were into herbs as well! How beautiful is that Planty theme. I'm going to launch a killer JAMstack e-commerce store using this for sure."
                          : "Word. But good code can  solve a lots of problems, too. New and old. That’s why we help beginners get started with web development through free content and tools, like this theme. We also believe the JAMstack might be one solid pillar on which we build that future."}
                      </div>
                    </p.Stack>
                    <div
                      className={classNames(projectcss.all, sty.column___8LoQw)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__t9Dn)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "400px"
                            : "500px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "100%"
                            : "100%"
                        }
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? "500px"
                            : "500px"
                        }
                        loading={"lazy"}
                        src={{
                          src: teamwebpGOvwC2TNreKQk7,
                          fullWidth: 1368,
                          fullHeight: 2048,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </p.Stack>
                </div>
              ) : null}
            </div>
          ) : null}
          <Footer className={classNames("__wab_instance", sty.footer__xzahJ)} />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "h1",
    "header",
    "featureItem",
    "bigPlants",
    "cactuses",
    "weLove",
    "weThink"
  ],

  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  header: ["header", "featureItem"],
  featureItem: ["featureItem"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  weLove: ["weLove"],
  weThink: ["weThink"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    header: makeNodeComponent("header"),
    featureItem: makeNodeComponent("featureItem"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    weLove: makeNodeComponent("weLove"),
    weThink: makeNodeComponent("weThink"),
    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
